# Generated by Django 3.2.6 on 2022-07-15 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseApp', '0006_delete_chicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudApadrinamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_estado', models.SmallIntegerField(blank=True, verbose_name='cod_estado')),
                ('motivo_FS', models.CharField(blank=True, max_length=500, null=True, verbose_name='motivo_apadrinamiento')),
                ('fecha_creacion', models.DateTimeField(blank=True, verbose_name='fecha_creacion')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha_aceptacion')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha_cancelacion')),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion')),
                ('dni_frente', models.ImageField(blank=True, max_length=50, null=True, upload_to='', verbose_name='dni_frente')),
                ('dni_dorso', models.ImageField(blank=True, max_length=50, null=True, upload_to='', verbose_name='dni_dorso')),
                ('recibo_sueldo', models.FileField(blank=True, max_length=50, null=True, upload_to='', verbose_name='recibo_sueldo')),
                ('acta_matrimonio', models.FileField(blank=True, max_length=50, null=True, upload_to='', verbose_name='acta_matrimonio')),
                ('visita', models.BooleanField(default=False, null=True, verbose_name='visita')),
                ('fecha_visita', models.DateTimeField(blank=True, null=True, verbose_name='fecha_visita')),
            ],
        ),
        migrations.CreateModel(
            name='Chicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='apellido')),
                ('edad', models.SmallIntegerField(blank=True, verbose_name='cant_empleados')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='descripcion')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='', verbose_name='fotografia')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseApp.institucion', verbose_name='institucion')),
            ],
        ),
    ]
