# Generated by Django 3.2.6 on 2022-07-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApadrinamientoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudapadrinamiento',
            name='chico_apadrinado',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chico_apadrinado', to='ApadrinamientoApp.chicos', verbose_name='id_chico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chicos',
            name='edad',
            field=models.SmallIntegerField(blank=True, verbose_name='edad'),
        ),
    ]
