# Generated by Django 3.2.6 on 2022-07-31 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_delete_chicos'),
        ('ApadrinamientoApp', '0002_auto_20220724_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicos',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.institucion', verbose_name='institucion'),
        ),
        migrations.AlterField(
            model_name='solicitudapadrinamiento',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='motivo_cancelacion'),
        ),
    ]
