# Generated by Django 3.2.6 on 2022-09-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApadrinamientoApp', '0004_auto_20220907_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudapadrinamiento',
            name='institucion',
        ),
    ]
