# Generated by Django 3.2.6 on 2023-01-21 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_auto_20220922_1951'),
        ('ApadrinamientoApp', '0005_remove_solicitudapadrinamiento_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicos',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chicos', to='baseApp.institucion', verbose_name='chicos'),
        ),
    ]
