# Generated by Django 3.2.6 on 2022-02-19 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='director')),
                ('fecha_fundacion', models.DateField(blank=True, null=True, verbose_name='fecha_fundacion')),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True, verbose_name='domicilio')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='ciudad')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='provincia')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='pais')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='telefono')),
                ('cant_empleados', models.SmallIntegerField(blank=True, null=True, verbose_name='cant_empleados')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='descripción')),
                ('cbu', models.BigIntegerField(blank=True, null=True, verbose_name='CBU')),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=12, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_institucion', to=settings.AUTH_USER_MODEL, verbose_name='id_usuario')),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha_nacimiento')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, verbose_name='dni')),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True, verbose_name='domicilio')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='ciudad')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='provincia')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='pais')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='telefono')),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True, verbose_name='provincia')),
                ('genero', models.CharField(blank=True, max_length=20, null=True, verbose_name='genero')),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='ocupacion')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_donante', to=settings.AUTH_USER_MODEL, verbose_name='id_usuario')),
            ],
            options={
                'verbose_name': 'Donante',
                'verbose_name_plural': 'Donantes',
                'ordering': ['nombre'],
            },
        ),
    ]
