# Generated by Django 3.2.6 on 2022-04-14 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_auto_20220224_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='apellido')),
                ('edad', models.SmallIntegerField(blank=True, verbose_name='cant_empleados')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='descripcion')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseApp.institucion', verbose_name='institucion')),
            ],
        ),
    ]
