# Generated by Django 3.2.6 on 2022-06-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_chicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha_nacimiento')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, verbose_name='dni')),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True, verbose_name='domicilio')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='ciudad')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='provincia')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='pais')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='telefono')),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True, verbose_name='provincia')),
                ('genero', models.CharField(blank=True, max_length=20, null=True, verbose_name='genero')),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='ocupacion')),
                ('medio_transporte', models.CharField(blank=True, max_length=100, null=True, verbose_name='medio-de-transporte')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseApp.institucion', verbose_name='institucion')),
            ],
            options={
                'verbose_name': 'Cadete',
                'verbose_name_plural': 'Cadetes',
                'ordering': ['nombre'],
            },
        ),
    ]
