# Generated by Django 3.2.6 on 2022-06-12 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseApp', '0004_cadete'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadete',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cadete', to=settings.AUTH_USER_MODEL, verbose_name='id_usuario'),
        ),
    ]
