# Generated by Django 3.2.6 on 2022-07-15 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_cadete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chicos',
        ),
    ]
