# Generated by Django 3.2.6 on 2022-09-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_delete_chicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='cuenta_bancaria',
        ),
        migrations.AlterField(
            model_name='institucion',
            name='cbu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CBU'),
        ),
    ]
