# Generated by Django 3.2.6 on 2023-08-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_auto_20220922_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='habilitado',
            field=models.BooleanField(default=False, verbose_name='institucion_habilitada'),
        ),
    ]
