# Generated by Django 3.2.6 on 2023-09-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0009_institucion_codigo_habilitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='codigo_habilitacion',
            field=models.CharField(blank=True, default='fce1d4f0f3ac34db1eac', max_length=20, verbose_name='codigo_habilitacion'),
        ),
    ]
