# Generated by Django 3.2.6 on 2023-10-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0010_alter_institucion_codigo_habilitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='codigo_habilitacion',
            field=models.CharField(blank=True, max_length=20, verbose_name='codigo_habilitacion'),
        ),
    ]
