# Generated by Django 3.2.6 on 2022-07-17 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseApp', '0005_cadete_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='reaccion')),
            ],
            options={
                'verbose_name': 'Reaccion',
                'verbose_name_plural': 'Reacciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('descripcion', models.CharField(max_length=500, verbose_name='descripcion')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha_publicacion')),
                ('autores', models.CharField(max_length=250, verbose_name='autores')),
                ('etiquetas', models.ManyToManyField(to='noticias.Etiqueta')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseApp.institucion', verbose_name='institucion_publicacion')),
                ('reacciones', models.ManyToManyField(to='noticias.Reaccion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario_publicacion')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['institucion', 'fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.CharField(max_length=500, verbose_name='comentario')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha_publicacion')),
                ('comentario_dirigido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.comentariopublicacion')),
                ('noticia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noticias.noticia', verbose_name='noticia_publicacion')),
                ('reacciones', models.ManyToManyField(to='noticias.Reaccion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario_publicacion')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['noticia', 'fecha_publicacion'],
            },
        ),
    ]
