# Generated by Django 3.2.6 on 2022-07-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopublicacion',
            name='comentario_dirigido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noticias.comentariopublicacion'),
        ),
        migrations.AlterField(
            model_name='comentariopublicacion',
            name='reacciones',
            field=models.ManyToManyField(to='noticias.Reaccion', verbose_name='reacciones_comentario'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='etiqueta'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='etiquetas',
            field=models.ManyToManyField(to='noticias.Etiqueta', verbose_name='etiquetas_noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='reacciones',
            field=models.ManyToManyField(to='noticias.Reaccion', verbose_name='reacciones_noticias'),
        ),
    ]
