# Generated by Django 3.2.6 on 2022-07-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20220724_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopublicacion',
            name='reacciones',
            field=models.ManyToManyField(null=True, to='noticias.Reaccion', verbose_name='reacciones_comentario'),
        ),
    ]
