# Generated by Django 3.2.6 on 2022-07-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_comentariopublicacion_reacciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopublicacion',
            name='reacciones',
            field=models.ManyToManyField(to='noticias.Reaccion', verbose_name='reacciones_comentario'),
        ),
    ]
