# Generated by Django 3.2.6 on 2022-07-24 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0004_alter_comentariopublicacion_reacciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopublicacion',
            name='comentario_dirigido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario_comentario', to='noticias.comentariopublicacion'),
        ),
        migrations.AlterField(
            model_name='comentariopublicacion',
            name='noticia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticia_comentario', to='noticias.noticia', verbose_name='noticia_comentario'),
        ),
        migrations.AlterField(
            model_name='comentariopublicacion',
            name='reacciones',
            field=models.ManyToManyField(related_name='reacciones_comentario', to='noticias.Reaccion', verbose_name='reacciones_comentario'),
        ),
        migrations.AlterField(
            model_name='comentariopublicacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_publicacion', to=settings.AUTH_USER_MODEL, verbose_name='usuario_publicacion'),
        ),
    ]
