# Generated by Django 3.2.6 on 2022-02-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20220126_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='director')),
                ('fecha_fundacion', models.DateField(blank=True, null=True, verbose_name='fecha_fundacion')),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True, verbose_name='domicilio')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='ciudad')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='provincia')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='pais')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='telefono')),
                ('cant_empleados', models.SmallIntegerField(blank=True, null=True, verbose_name='cant_empleados')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='descripción')),
                ('cbu', models.BigIntegerField(blank=True, null=True, verbose_name='CBU')),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre'],
            },
        ),
    ]
