# Generated by Django 3.2.6 on 2022-02-09 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usua', to=settings.AUTH_USER_MODEL, verbose_name='id_usuario'),
        ),
    ]
