# Generated by Django 3.2.6 on 2022-02-09 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0004_institucion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_donante', to=settings.AUTH_USER_MODEL, verbose_name='id_usuario'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_institucion', to=settings.AUTH_USER_MODEL, verbose_name='id_usuario'),
        ),
    ]
