# Generated by Django 3.2.6 on 2022-02-17 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_auto_20220209_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='codigoRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='mail_usuario')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='codigo_recuperacion')),
                ('activo', models.BooleanField(blank=True, verbose_name='codigo_activo')),
                ('fecha_expiracion', models.DateField(blank=True, verbose_name='fecha_expiracion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_codigo_recuperacion', to=settings.AUTH_USER_MODEL, verbose_name='id_usuario')),
            ],
        ),
    ]
