# Generated by Django 3.2.6 on 2022-02-24 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0007_auto_20220218_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigorecuperacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_codigo_recuperacion', to=settings.AUTH_USER_MODEL, verbose_name='id_usuario_codigo_recuperacion'),
        ),
        migrations.CreateModel(
            name='paseInvitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(blank=True, verbose_name='fecha_alta')),
                ('nombre_invitado', models.CharField(blank=True, max_length=50, verbose_name='nombre_invitado')),
                ('email_invitado', models.EmailField(blank=True, max_length=255, verbose_name='mail_invitado')),
                ('codigo_pase', models.CharField(blank=True, max_length=20, verbose_name='codigo_recuperacion')),
                ('estado', models.IntegerField(blank=True, verbose_name='codigo_estado')),
                ('activo', models.BooleanField(blank=True, verbose_name='pase_activo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_que_invita', to=settings.AUTH_USER_MODEL, verbose_name='id_usuario')),
            ],
        ),
    ]
