# Generated by Django 3.2.6 on 2021-10-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('edad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Donante',
                'verbose_name_plural': 'Donantes',
                'ordering': ['nombre'],
            },
        ),
    ]
