# Generated by Django 3.2.6 on 2022-06-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_recoleccion', models.SmallIntegerField(blank=True, verbose_name='estado')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha_cancelacion')),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'Recolección',
                'verbose_name_plural': 'Recolecciones',
            },
        ),
    ]
