# Generated by Django 3.2.6 on 2022-06-23 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_cadete_usuario'),
        ('Recoleccion', '0002_auto_20220623_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoleccion',
            name='cadete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseApp.cadete', verbose_name='cadete'),
        ),
    ]
