# Generated by Django 3.2.6 on 2022-07-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recoleccion', '0003_recoleccion_cadete'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoleccion',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha_finalizacion'),
        ),
    ]
