# Generated by Django 3.2.6 on 2022-09-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recoleccion', '0004_recoleccion_fecha_finalizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recoleccion',
            options={'ordering': ['fecha_recoleccion'], 'verbose_name': 'Recolección', 'verbose_name_plural': 'Recolecciones'},
        ),
    ]
