# Generated by Django 3.2.6 on 2022-09-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recoleccion', '0005_alter_recoleccion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoleccion',
            name='fecha_inicio_recoleccion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha_inicio_recoleccion'),
        ),
    ]
