# Generated by Django 3.2.6 on 2022-09-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recoleccion', '0006_recoleccion_fecha_inicio_recoleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoleccion',
            name='fecha_inicio_recoleccion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha_inicio_recoleccion'),
        ),
    ]
