# Generated by Django 3.2.6 on 2022-03-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseApp', '0002_auto_20220224_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(blank=True, verbose_name='fecha_creacion')),
                ('fecha_aceptacion', models.DateField(blank=True, verbose_name='fecha_aceptacion')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='fecha_entrega')),
                ('cod_estado', models.SmallIntegerField(blank=True, verbose_name='estado')),
                ('donante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseApp.donante', verbose_name='donante')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseApp.institucion', verbose_name='institución')),
            ],
        ),
        migrations.CreateModel(
            name='DonacionBienes',
            fields=[
                ('donacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DonacionesApp.donacion')),
                ('fecha_retiro', models.DateField(blank=True, null=True, verbose_name='fecha_retiro')),
            ],
            bases=('DonacionesApp.donacion',),
        ),
        migrations.CreateModel(
            name='DonacionMonetaria',
            fields=[
                ('donacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DonacionesApp.donacion')),
                ('monto', models.FloatField(blank=True, verbose_name='monto')),
                ('fecha_transferencia', models.DateField(blank=True, verbose_name='fecha_transferencia')),
            ],
            bases=('DonacionesApp.donacion',),
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[(1, 'alimento'), (2, 'útil'), (3, 'prenda'), (4, 'otro')], max_length=2)),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='descripcion')),
                ('cantidad', models.IntegerField(blank=True, verbose_name='cantidad')),
                ('donacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DonacionesApp.donacionbienes', verbose_name='donacion_bienes')),
            ],
        ),
    ]
