# Generated by Django 3.2.6 on 2022-03-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonacionesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha_aceptacion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha_aceptacion'),
        ),
    ]
