# Generated by Django 3.2.6 on 2022-04-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonacionesApp', '0002_alter_donacion_fecha_aceptacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, verbose_name='fecha_creacion'),
        ),
    ]
