# Generated by Django 3.2.6 on 2022-06-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DonacionesApp', '0006_auto_20220506_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bien',
            options={'ordering': ['tipo'], 'verbose_name': 'Bien', 'verbose_name_plural': 'Bienes'},
        ),
        migrations.AlterModelOptions(
            name='donacion',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Donación', 'verbose_name_plural': 'Donaciones'},
        ),
        migrations.AlterModelOptions(
            name='donacionbienes',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Donación de bienes', 'verbose_name_plural': 'Donaciones de bienes'},
        ),
        migrations.AlterModelOptions(
            name='donacionmonetaria',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Donación monetaria', 'verbose_name_plural': 'Donaciones monetarias'},
        ),
    ]
