# Generated by Django 3.2.6 on 2022-06-19 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recoleccion', '0001_initial'),
        ('DonacionesApp', '0007_auto_20220615_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacionbienes',
            name='recoleccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones', to='Recoleccion.recoleccion'),
        ),
    ]
