# Generated by Django 3.2.6 on 2022-08-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonacionesApp', '0008_donacionbienes_recoleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, verbose_name='descripcion'),
        ),
    ]
