# Generated by Django 3.2.6 on 2022-09-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonacionesApp', '0009_alter_bien_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='cod_estado',
            field=models.SmallIntegerField(blank=True, verbose_name='cod_estado'),
        ),
    ]
