# Generated by Django 3.2.6 on 2023-06-03 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_auto_20220922_1951'),
        ('DonacionesApp', '0010_alter_donacion_cod_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Necesidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[(1, 'alimento'), (2, 'útil'), (3, 'prenda'), (4, 'otro'), (0, 'monetaria')], max_length=2)),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='titulo')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='descripcion')),
                ('cantidad', models.IntegerField(blank=True, verbose_name='cantidad')),
                ('fecha_alta', models.DateTimeField(blank=True, verbose_name='fecha_alta')),
                ('fecha_vigencia', models.DateTimeField(blank=True, null=True, verbose_name='fecha_vigencia')),
                ('fecha_baja', models.DateTimeField(blank=True, null=True, verbose_name='fecha_baja')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidad', to='baseApp.institucion')),
            ],
            options={
                'verbose_name': 'Necesidad',
                'verbose_name_plural': 'Necesidades',
                'ordering': ['fecha_alta'],
            },
        ),
    ]
