# Generated by Django 3.2.6 on 2023-07-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonacionesApp', '0011_necesidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='necesidad',
            name='isDelete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='isDelete'),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha_alta'),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo'),
        ),
    ]
