# Generated by Django 3.2.6 on 2023-08-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonacionesApp', '0012_auto_20230721_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='observacion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='observacion'),
        ),
    ]
