# Generated by Django 3.2.6 on 2023-08-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonacionesApp', '0013_donacion_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacionmonetaria',
            name='comprobante_transaccion',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to='', verbose_name='comprobante_transaccion'),
        ),
    ]
