# Generated by Django 3.2.6 on 2023-08-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonacionesApp', '0014_donacionmonetaria_comprobante_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacionbienes',
            name='tipo',
            field=models.CharField(choices=[(1, 'Retirar'), (2, 'Envio'), (3, 'Contactar Institución')], default=None, max_length=2),
            preserve_default=False,
        ),
    ]
