# Generated by Django 3.2.6 on 2023-10-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonacionesApp', '0015_donacionbienes_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='necesidad',
            name='cumplida',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='isCumplida'),
        ),
    ]
